"""
╔══════════════════════════════════════════════════════════════════╗
║         3D KEPLERIAN ORBITAL MECHANICS SIMULATOR                 ║
║         ModernGL + GLFW + NumPy                                  ║
╠══════════════════════════════════════════════════════════════════╣
║  SETUP:                                                          ║
║    pip install moderngl glfw numpy                               ║
║    python main.py                                                ║
╠══════════════════════════════════════════════════════════════════╣
║  CONTROLS:                                                       ║
║    Mouse drag        Orbit camera                                ║
║    Scroll wheel      Zoom in/out                                 ║
║    WASD              Pan camera                                  ║
║    ↑ / ↓             Speed up / slow down satellite             ║
║    ← / →             Rotate velocity in orbital plane           ║
║    I / K             Tilt orbit inclination (+/-)               ║
║    C                 Snap to circular orbit                      ║
║    E                 Snap to escape velocity                     ║
║    R                 Reset simulation                            ║
║    SPACE             Pause / Resume                              ║
║    F / S             Fast / Slow time                            ║
║    1 / 2 / 3         Preset orbits (circular/elliptical/escape)  ║
╚══════════════════════════════════════════════════════════════════╝

KEY 3D MATH CONCEPTS:
─────────────────────
• All positions/velocities are 3-component NumPy vectors [x, y, z]
• Gravity: F = -GM/|r|³ · r  (scalar magnitude × unit direction)
• Verlet integration works identically in 3D — just use np.array math
• Inclined orbits: initial velocity has a Z-component → orbit tilts out of XY plane
• Camera: uses spherical coordinates (radius, theta, phi) → converted to
  Cartesian for view matrix. Mouse drag changes theta/phi.
• Projection: standard perspective matrix (FOV, aspect, near, far)
• View matrix: lookAt(eye, target, up) — standard OpenGL camera math
• Earth sphere: generated by latitude/longitude tessellation
• Lighting: Blinn-Phong (ambient + diffuse + specular) in fragment shader
"""

import sys
import glfw
import moderngl
import numpy as np
import math
import time

from physics import PhysicsEngine, OrbitalBody, PRESETS
from camera  import Camera
from renderer import Renderer


# ── Window config ──────────────────────────────────────────────────
WIDTH, HEIGHT = 1280, 800
TITLE = "3D Orbital Mechanics Simulator"


def main():
    # ── Init GLFW ──────────────────────────────────────────────────
    if not glfw.init():
        print("GLFW init failed"); sys.exit(1)

    glfw.window_hint(glfw.CONTEXT_VERSION_MAJOR, 3)
    glfw.window_hint(glfw.CONTEXT_VERSION_MINOR, 3)
    glfw.window_hint(glfw.OPENGL_PROFILE, glfw.OPENGL_CORE_PROFILE)
    glfw.window_hint(glfw.OPENGL_FORWARD_COMPAT, True)  # macOS
    glfw.window_hint(glfw.SAMPLES, 4)  # MSAA

    window = glfw.create_window(WIDTH, HEIGHT, TITLE, None, None)
    if not window:
        glfw.terminate(); print("Window creation failed"); sys.exit(1)

    glfw.make_context_current(window)
    glfw.swap_interval(1)  # vsync

    # ── ModernGL context ───────────────────────────────────────────
    ctx = moderngl.create_context()
    ctx.enable(moderngl.DEPTH_TEST | moderngl.BLEND)
    ctx.blend_func = moderngl.SRC_ALPHA, moderngl.ONE_MINUS_SRC_ALPHA

    # ── Subsystems ─────────────────────────────────────────────────
    physics  = PhysicsEngine()
    camera   = Camera(distance=6.0)
    renderer = Renderer(ctx, WIDTH, HEIGHT)

    # ── Input state ────────────────────────────────────────────────
    mouse = {"last_x": 0, "last_y": 0, "dragging": False}

    def on_mouse_button(win, button, action, mods):
        if button == glfw.MOUSE_BUTTON_LEFT:
            mouse["dragging"] = (action == glfw.PRESS)
            x, y = glfw.get_cursor_pos(win)
            mouse["last_x"], mouse["last_y"] = x, y

    def on_cursor_pos(win, x, y):
        if mouse["dragging"]:
            dx = x - mouse["last_x"]
            dy = y - mouse["last_y"]
            camera.orbit(dx * 0.4, dy * 0.4)
        mouse["last_x"], mouse["last_y"] = x, y

    def on_scroll(win, xoff, yoff):
        camera.zoom(-yoff * 0.4)

    def on_resize(win, w, h):
        ctx.viewport = (0, 0, w, h)
        renderer.update_projection(w, h)

    glfw.set_mouse_button_callback(window, on_mouse_button)
    glfw.set_cursor_pos_callback(window, on_cursor_pos)
    glfw.set_scroll_callback(window, on_scroll)
    glfw.set_framebuffer_size_callback(window, on_resize)

    # ── Timing ─────────────────────────────────────────────────────
    last_time  = time.perf_counter()
    dt_mult    = 1.0
    paused     = False
    DT_BASE    = 0.008   # physics timestep (seconds of sim time per frame step)
    STEPS_PER_FRAME = 8  # sub-steps per frame for accuracy

    # ── Main loop ──────────────────────────────────────────────────
    while not glfw.window_should_close(window):
        now       = time.perf_counter()
        wall_dt   = min(now - last_time, 0.05)
        last_time = now

        glfw.poll_events()

        # ── Held-key controls ──────────────────────────────────────
        sat = physics.satellite
        if not paused:
            boost = 0.008
            if glfw.get_key(window, glfw.KEY_UP)    == glfw.PRESS:
                sat.vel *= (1 + boost); sat.clear_trail()
            if glfw.get_key(window, glfw.KEY_DOWN)  == glfw.PRESS:
                sat.vel *= max(0.01, 1 - boost); sat.clear_trail()
            if glfw.get_key(window, glfw.KEY_LEFT)  == glfw.PRESS:
                sat.rotate_vel_in_plane(-1.5); sat.clear_trail()
            if glfw.get_key(window, glfw.KEY_RIGHT) == glfw.PRESS:
                sat.rotate_vel_in_plane( 1.5); sat.clear_trail()
            if glfw.get_key(window, glfw.KEY_I) == glfw.PRESS:
                sat.tilt_orbit( 0.5); sat.clear_trail()
            if glfw.get_key(window, glfw.KEY_K) == glfw.PRESS:
                sat.tilt_orbit(-0.5); sat.clear_trail()

        if glfw.get_key(window, glfw.KEY_A) == glfw.PRESS: camera.pan(-0.03, 0)
        if glfw.get_key(window, glfw.KEY_D) == glfw.PRESS: camera.pan( 0.03, 0)
        if glfw.get_key(window, glfw.KEY_W) == glfw.PRESS: camera.pan(0,  0.03)
        if glfw.get_key(window, glfw.KEY_S) == glfw.PRESS: camera.pan(0, -0.03)

        # ── One-shot key events (polled manually via sticky) ───────
        # (handled via key callback below)

        # ── Physics update ─────────────────────────────────────────
        if not paused and not sat.escaped:
            for _ in range(STEPS_PER_FRAME):
                physics.step(DT_BASE * dt_mult)

        # ── Render ─────────────────────────────────────────────────
        ctx.clear(0.03, 0.04, 0.07, 1.0)
        view, proj = camera.matrices()
        renderer.render(ctx, physics, camera, view, proj)

        glfw.swap_buffers(window)

    glfw.terminate()


# ── One-shot key callback (set after main loop vars defined) ───────
# We use a closure trick — define it inside main() scope
def _attach_key_callback(window, physics, camera_ref, dt_mult_ref, paused_ref):
    """Attach keyboard callback. dt_mult_ref and paused_ref are single-element lists."""
    def on_key(win, key, scancode, action, mods):
        if action != glfw.PRESS:
            return
        sat = physics.satellite
        if key == glfw.KEY_SPACE:
            paused_ref[0] = not paused_ref[0]
        elif key == glfw.KEY_R:
            physics.reset()
            dt_mult_ref[0] = 1.0
        elif key == glfw.KEY_C:
            sat.snap_circular()
        elif key == glfw.KEY_E:
            sat.snap_escape()
        elif key == glfw.KEY_F:
            dt_mult_ref[0] = min(dt_mult_ref[0] * 1.5, 10.0)
        elif key == glfw.KEY_S and (mods & glfw.MOD_SHIFT) == 0:
            dt_mult_ref[0] = max(dt_mult_ref[0] / 1.5, 0.1)
        elif key == glfw.KEY_1:
            physics.load_preset("circular")
        elif key == glfw.KEY_2:
            physics.load_preset("elliptical")
        elif key == glfw.KEY_3:
            physics.load_preset("escape")
        elif key == glfw.KEY_4:
            physics.load_preset("inclined")
        elif key == glfw.KEY_ESCAPE:
            glfw.set_window_should_close(win, True)
    return on_key


# Re-do main() properly with closures
def main():  # noqa: F811
    if not glfw.init():
        print("GLFW init failed"); sys.exit(1)

    glfw.window_hint(glfw.CONTEXT_VERSION_MAJOR, 3)
    glfw.window_hint(glfw.CONTEXT_VERSION_MINOR, 3)
    glfw.window_hint(glfw.OPENGL_PROFILE, glfw.OPENGL_CORE_PROFILE)
    glfw.window_hint(glfw.OPENGL_FORWARD_COMPAT, True)
    glfw.window_hint(glfw.SAMPLES, 4)

    window = glfw.create_window(WIDTH, HEIGHT, TITLE, None, None)
    if not window:
        glfw.terminate(); sys.exit(1)

    glfw.make_context_current(window)
    glfw.swap_interval(1)

    ctx = moderngl.create_context()
    ctx.enable(moderngl.DEPTH_TEST | moderngl.BLEND)
    ctx.blend_func = moderngl.SRC_ALPHA, moderngl.ONE_MINUS_SRC_ALPHA

    physics  = PhysicsEngine()
    camera   = Camera(distance=6.0)
    renderer = Renderer(ctx, WIDTH, HEIGHT)

    dt_mult = [1.0]
    paused  = [False]

    mouse = {"last_x": 0.0, "last_y": 0.0, "dragging": False}

    def on_mouse_button(win, button, action, mods):
        if button == glfw.MOUSE_BUTTON_LEFT:
            mouse["dragging"] = (action == glfw.PRESS)
            x, y = glfw.get_cursor_pos(win)
            mouse["last_x"], mouse["last_y"] = x, y

    def on_cursor_pos(win, x, y):
        if mouse["dragging"]:
            dx = x - mouse["last_x"]
            dy = y - mouse["last_y"]
            camera.orbit(dx * 0.35, dy * 0.35)
        mouse["last_x"], mouse["last_y"] = x, y

    def on_scroll(win, xoff, yoff):
        camera.zoom(-yoff * 0.35)

    def on_resize(win, w, h):
        if w > 0 and h > 0:
            ctx.viewport = (0, 0, w, h)
            renderer.update_projection(w, h)

    glfw.set_mouse_button_callback(window, on_mouse_button)
    glfw.set_cursor_pos_callback(window, on_cursor_pos)
    glfw.set_scroll_callback(window, on_scroll)
    glfw.set_framebuffer_size_callback(window, on_resize)

    key_cb = _attach_key_callback(window, physics, camera, dt_mult, paused)
    glfw.set_key_callback(window, key_cb)

    DT_BASE = 0.008
    STEPS   = 8
    last_t  = time.perf_counter()

    while not glfw.window_should_close(window):
        now    = time.perf_counter()
        last_t = now
        glfw.poll_events()

        sat = physics.satellite

        # Held-key controls
        if not paused[0]:
            boost = 0.006
            if glfw.get_key(window, glfw.KEY_UP)    == glfw.PRESS:
                sat.vel = sat.vel * (1 + boost); sat.clear_trail()
            if glfw.get_key(window, glfw.KEY_DOWN)  == glfw.PRESS:
                sat.vel = sat.vel * max(0.01, 1 - boost); sat.clear_trail()
            if glfw.get_key(window, glfw.KEY_LEFT)  == glfw.PRESS:
                sat.rotate_vel_in_plane(-1.2); sat.clear_trail()
            if glfw.get_key(window, glfw.KEY_RIGHT) == glfw.PRESS:
                sat.rotate_vel_in_plane( 1.2); sat.clear_trail()
            if glfw.get_key(window, glfw.KEY_I)     == glfw.PRESS:
                sat.tilt_orbit( 0.4); sat.clear_trail()
            if glfw.get_key(window, glfw.KEY_K)     == glfw.PRESS:
                sat.tilt_orbit(-0.4); sat.clear_trail()

        if glfw.get_key(window, glfw.KEY_A) == glfw.PRESS: camera.pan(-0.025, 0)
        if glfw.get_key(window, glfw.KEY_D) == glfw.PRESS: camera.pan( 0.025, 0)
        if glfw.get_key(window, glfw.KEY_W) == glfw.PRESS: camera.pan(0,  0.025)
        if glfw.get_key(window, glfw.KEY_S) == glfw.PRESS: camera.pan(0, -0.025)

        if not paused[0] and not sat.escaped:
            for _ in range(STEPS):
                physics.step(DT_BASE * dt_mult[0])

        ctx.clear(0.02, 0.03, 0.06, 1.0)
        view, proj = camera.matrices()
        renderer.render(ctx, physics, camera, view, proj, paused[0], dt_mult[0])
        glfw.swap_buffers(window)

    glfw.terminate()


if __name__ == "__main__":
    main()